//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAODSHD_NGAY
    {
        public int MaBCDSHD { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public Nullable<int> MaLoaiSTK { get; set; }
        public Nullable<decimal> TongThu { get; set; }
        public Nullable<decimal> TongChi { get; set; }
        public Nullable<decimal> ChenhLech { get; set; }
    
        public virtual LOAISOTIETKIEM LOAISOTIETKIEM { get; set; }
    }
}
