//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BCMODONGSO_THANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BCMODONGSO_THANG()
        {
            this.CT_BCMODONGSO_THANG = new HashSet<CT_BCMODONGSO_THANG>();
        }
    
        public int MaBCMODONGSO { get; set; }
        public Nullable<int> MaLoaiSTK { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
    
        public virtual LOAISOTIETKIEM LOAISOTIETKIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BCMODONGSO_THANG> CT_BCMODONGSO_THANG { get; set; }
    }
}
