//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BCMODONGSO_THANG
    {
        public int MaBCMODONGSO { get; set; }
        public int Ngay { get; set; }
        public Nullable<int> SoSoMo { get; set; }
        public Nullable<int> SoSoDong { get; set; }
        public Nullable<int> ChenhLech { get; set; }
    
        public virtual BCMODONGSO_THANG BCMODONGSO_THANG { get; set; }
    }
}
