//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliteria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ELITERIAEntities : DbContext
    {
        public ELITERIAEntities()
            : base("name=ELITERIAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BAOCAODSHD_NGAY> BAOCAODSHD_NGAY { get; set; }
        public virtual DbSet<BCMODONGSO_THANG> BCMODONGSO_THANG { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<CT_BCMODONGSO_THANG> CT_BCMODONGSO_THANG { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAIGIAODICH> LOAIGIAODICHes { get; set; }
        public virtual DbSet<LOAISOTIETKIEM> LOAISOTIETKIEMs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUGIAODICH> PHIEUGIAODICHes { get; set; }
        public virtual DbSet<SOTIETKIEM> SOTIETKIEMs { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
