//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAISOTIETKIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LOAISOTIETKIEM()
        {
            this.BAOCAODSHD_NGAY = new HashSet<BAOCAODSHD_NGAY>();
            this.BCMODONGSO_THANG = new HashSet<BCMODONGSO_THANG>();
            this.SOTIETKIEMs = new HashSet<SOTIETKIEM>();
        }
    
        public int MaLoaiSTK { get; set; }
        public string TenLoaiSTK { get; set; }
        public int KyHan { get; set; }
        public float LaiSuat { get; set; }
        public System.DateTime NgayApDung { get; set; }
        public int SoNgayToiDuocRutTien { get; set; }
        public string QDSoTienDuocRut { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BAOCAODSHD_NGAY> BAOCAODSHD_NGAY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCMODONGSO_THANG> BCMODONGSO_THANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SOTIETKIEM> SOTIETKIEMs { get; set; }
    }
}
