//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUGIAODICH
    {
        public int MaPhieuGD { get; set; }
        public int MaLoaiGD { get; set; }
        public Nullable<int> MaSTK { get; set; }
        public Nullable<int> MaNV { get; set; }
        public Nullable<System.DateTime> NgayLapPhieu { get; set; }
        public Nullable<decimal> SoTien { get; set; }
    
        public virtual LOAIGIAODICH LOAIGIAODICH { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual SOTIETKIEM SOTIETKIEM { get; set; }
    }
}
