//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eliteria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOTIETKIEM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOTIETKIEM()
        {
            this.PHIEUGIAODICHes = new HashSet<PHIEUGIAODICH>();
        }
    
        public int MaSTK { get; set; }
        public int MaKH { get; set; }
        public int MaLoaiSTK { get; set; }
        public System.DateTime NgayMoSo { get; set; }
        public decimal TongSoTienDaGui { get; set; }
        public decimal TongSoTienDaRut { get; set; }
        public decimal TienLaiPhatSinh { get; set; }
        public decimal SoDu { get; set; }
        public System.DateTime NgayDaoHanKeTiep { get; set; }
        public float LaiSuatApDung { get; set; }
        public bool TrangThai { get; set; }
        public Nullable<System.DateTime> NgayDongSo { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual LOAISOTIETKIEM LOAISOTIETKIEM { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUGIAODICH> PHIEUGIAODICHes { get; set; }
    }
}
